apiVersion: apps/v1
kind: Deployment

metadata:
  name: bloghub
  namespace: bloghub

spec:
  replicas: 2

  selector:
    matchLabels:
      app: bloghub

  template:
    metadata:
      labels:
        app: bloghub

    spec:
      imagePullSecrets:
        - name: ecr-secret

      containers:
        - name: bloghub
          image: 500782030335.dkr.ecr.ap-south-1.amazonaws.com/k8s:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8082

          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: bloghub-config
                  key: DATABASE_URL

            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

          readinessProbe:
            tcpSocket:
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 20
